### ISSUE TITLE
转换一切顺利，但是检测到的物体置信度为负数

### ISSUE THREAD

**Issue by Bin-ze** [Monday-Leo/YOLOv7_Tensorrt#6]
我按照您的readme在开发板上进行了模型部署，一切顺利，但是检测物体的置信度为负数，这是因为什么原因造成的，因为我没有在trt推理下评估模型的指标，所以我很难确定这样带来的性能影响，如果你可以回答我的疑问，我将很感激

**Comment by Monday-Leo** [comment]
因为tensorrt 8.2有bug。升级至8.4可以解决。

**Comment by Bin-ze** [comment]
这个bug为什么转换yolov5不出现，还有使用pip直接安装tensorrt不出现，只出现在自己源码安装tensorrt或许jston平台刷的tensorrt也有问题，感觉很奇怪


发自我的iPhone

**Comment by Monday-Leo** [comment]
这是nms的bug，yolov5的nms没有并入到模型当中，所以没关系。

**Comment by Bin-ze** [comment]
那我自己写nms，倒出无nms的onnx模型呢

发自我的iPhone

**Comment by Monday-Leo** [comment]
那就没有问题，甚至可以用tensorrt7，这个仓库主要是添加了efficientnms到模型中，所以才使用的tensorrt8.4。
